### ISSUE TITLE
Update to R 4.x

### ISSUE THREAD

**Issue by M-Colley** [vankesteren/firatheme#3]
Hi, when trying to install firatheme with a version > 4.0.0 (tried with 4.0.2 and 4.0.3) I receive the following message:

> Warning in install.packages :
  package ‘firatheme’ is not available for this version of R

Could you update firatheme and make it available for R >= 4.0.0?

Thank you in advance!

**Comment by vankesteren** [comment]
Hi M-Colley,

firatheme is not available on CRAN at all unfortunately. The best way to install firatheme is through the `remotes` package:

```r
remotes::install_github("vankesteren/firatheme")
```
